train:
  id: csgo
  size: [256,240]
num_actions: 4
path_data_low_res: /home/abodner/DIAMOND_SuperMario_cloud/diamond/processed/low_res
path_data_full_res: /home/abodner/DIAMOND_SuperMario_cloud/diamond/processed/full_res
keymap: csgo
